name: Matrix Build

on:
  push:
    paths:
      - '03-matrix-build/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run script
        run: python 03-matrix-build/matrix_script.py